export const skills = [
  "3D Modeling",
  "3D Printing",
  "3D Product Viz",
  "AI Development",
  "AI Ethics",
  "AI Infrastructure",
  "API Design",
  "API Development",
  "API Gateway",
  "AR Shopping",
  "AWS",
  "Accessibility",
  "Accessibility Testing",
  "Additive Manufacturing",
  "Alexa Skills",
  "Analytics",
  "Android Development",
  "Apollo",
  "App Design",
  "Augmented Reality",
  "Automated Testing",
  "Automation",
  "Automation Anywhere",
  "Azure",
  "B2B Software",
  "Backend Development",
  "Banking APIs",
  "Bio Data",
  "Bioinformatics",
  "Blockchain",
  "Branding",
  "Bubble.io",
  "Business Intelligence",
  "CAD Design",
  "CDN",
  "CI/CD",
  "CRO",
  "CSS Animation",
  "Caching",
  "Carbon Tracking",
  "City Planning",
  "Cloud Architecture",
  "Cloud Computing",
  "Cloud Gaming",
  "Community Management",
  "Computer Vision",
  "Content Creation",
  "Content Strategy",
  "Content Writing",
  "Conversational AI",
  "Core Web Vitals",
  "Corporate Training",
  "Cryptocurrency",
  "Cryptography",
  "Cybersecurity",
  "Data Analytics",
  "Data Privacy",
  "Data Protection",
  "Data Science",
  "Data Visualization",
  "Database Architecture",
  "DeFi",
  "Design Systems",
  "DevOps",
  "Digital Marketing",
  "Digital Strategy",
  "Digital Twin",
  "Distributed Systems",
  "Docker",
  "Drone Analytics",
  "Drone Software",
  "E-Learning",
  "E-commerce Strategy",
  "Edge AI",
  "Edge Computing",
  "Embedded Systems",
  "Energy Efficiency",
  "Ethical Computing",
  "Financial Software",
  "Fintech",
  "Firmware",
  "Flight Control",
  "Frontend Development",
  "Frontend Optimization",
  "GDPR Compliance",
  "Game Backend",
  "Game Design",
  "Game Development",
  "Game Streaming",
  "Gaming Infrastructure",
  "Genomics",
  "Google Actions",
  "GraphQL",
  "Graphic Design",
  "Green Tech",
  "Ground Systems",
  "Growth Hacking",
  "HIPAA Compliance",
  "Headless CMS",
  "Health Apps",
  "Healthcare Tech",
  "HoloLens",
  "Industrial IoT",
  "Infrastructure as Code",
  "Interaction Design",
  "IoT Analytics",
  "IoT Development",
  "IoT Hardware",
  "IoT Integration",
  "Jamstack",
  "Kubernetes",
  "Link Building",
  "Low-Code Development",
  "ML Pipeline",
  "MLOps",
  "MVP Development",
  "Machine Learning",
  "Medical Software",
  "Mendix",
  "Microservices",
  "Mixed Reality",
  "Mobile UI Design",
  "Mobile UX",
  "Model Deployment",
  "Motion Control",
  "Motion Graphics",
  "Netlify",
  "Network Optimization",
  "Neural Networks",
  "No-Code Development",
  "Offline First",
  "OutSystems",
  "PWA Development",
  "Payment Integration",
  "Penetration Testing",
  "Performance Optimization",
  "Performance Testing",
  "Post-Quantum Crypto",
  "Power Platform",
  "Privacy by Design",
  "Process Automation",
  "Product Design",
  "Product Strategy",
  "Prototyping",
  "QA Testing",
  "Quantum Algorithms",
  "Quantum Computing",
  "Quantum ML",
  "Quantum Research",
  "Quantum Security",
  "REST APIs",
  "ROS",
  "RPA",
  "RTOS",
  "React",
  "Responsible AI",
  "Retail Tech",
  "Robot Vision",
  "Robotics",
  "SEO",
  "SaaS Development",
  "Satellite Software",
  "Scientific Computing",
  "Screen Reader Optimization",
  "Security",
  "Security Auditing",
  "Security Compliance",
  "Security Testing",
  "Sensor Integration",
  "Service Mesh",
  "Service Workers",
  "Shopify",
  "Simulation",
  "Smart City",
  "Smart Contracts",
  "Social Media Marketing",
  "Software Development",
  "Space Data",
  "Space Tech",
  "Spatial Computing",
  "Startup Consulting",
  "Static Sites",
  "Sustainability",
  "System Design",
  "System Integration",
  "Technical Training",
  "TensorFlow Lite",
  "UI/UX Design",
  "UX Design",
  "UiPath",
  "Unity",
  "Unity Development",
  "Unity3D",
  "Unreal Engine",
  "Urban Tech",
  "Usability Testing",
  "User Research",
  "Virtual Reality",
  "Virtual Try-On",
  "Voice UI",
  "Vue.js",
  "WCAG Compliance",
  "Web Development",
  "Web Performance",
  "Web3",
  "Webflow",
  "WooCommerce",
  "Workshop Development",
  "iOS Development"
] as const;
